[package]
name = "library"
version = "0.1.0"
authors = ["Krisztian Kovacs <kkovaacs@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.2"
cgroups-rs = "0.2.4"
tempfile = "3.2.0"
tokio = { version = "1.2.0", features = ["io-util", "macros", "process", "rt", "sync", "fs"] }

[dev-dependencies]
tokio-stream = "0.1.3"
